/// Report Registry System
///
/// Tracks all generated reports across different tools for cross-tool discovery.
/// Enables tools to discover and reference reports generated by other tools.
///
/// ## Usage
/// ```dart
/// final registry = ReportRegistry();
///
/// // Register a report
/// registry.register(
///   reportPath: 'tests_reports/coverage/auth-fo_coverage@1234_051125.md',
///   toolName: 'analyze_coverage',
///   reportType: 'coverage',
///   moduleName: 'auth-fo',
/// );
///
/// // Query reports
/// final coverageReports = registry.getReports(reportType: 'coverage');
/// final authReports = registry.getReports(moduleName: 'auth-fo');
///
/// // Print summary
/// registry.printSummary();
/// ```

/// Represents a single registered report entry
class ReportEntry {
  ReportEntry({
    required this.reportPath,
    required this.toolName,
    required this.reportType,
    required this.moduleName,
    DateTime? timestamp,
  }) : timestamp = timestamp ?? DateTime.now();

  final String reportPath;
  final String toolName;
  final String reportType;
  final String moduleName;
  final DateTime timestamp;

  @override
  String toString() =>
      'ReportEntry(path=$reportPath, tool=$toolName, type=$reportType, module=$moduleName, timestamp=$timestamp)';
}

/// Central registry for tracking all generated reports
class ReportRegistry {
  final List<ReportEntry> _reports = [];

  /// Register a new report in the registry
  void register({
    required String reportPath,
    required String toolName,
    required String reportType,
    required String moduleName,
  }) {
    final entry = ReportEntry(
      reportPath: reportPath,
      toolName: toolName,
      reportType: reportType,
      moduleName: moduleName,
    );
    _reports.add(entry);
  }

  /// Get all registered reports, optionally filtered
  List<ReportEntry> getReports({
    String? toolName,
    String? reportType,
    String? moduleName,
  }) {
    var results = _reports.toList();

    if (toolName != null) {
      results = results.where((r) => r.toolName == toolName).toList();
    }

    if (reportType != null) {
      results = results.where((r) => r.reportType == reportType).toList();
    }

    if (moduleName != null) {
      results = results.where((r) => r.moduleName == moduleName).toList();
    }

    return results;
  }

  /// Print a summary of all registered reports
  void printSummary() {
    if (_reports.isEmpty) {
      print('📋 Report Registry: No reports registered');
      return;
    }

    print('\n${"═" * 70}');
    print('📋 REPORT REGISTRY SUMMARY');
    print('${"═" * 70}\n');

    print('Total Reports: ${_reports.length}');
    print('');

    // Group by tool
    final byTool = <String, List<ReportEntry>>{};
    for (final report in _reports) {
      byTool.putIfAbsent(report.toolName, () => []).add(report);
    }

    for (final entry in byTool.entries) {
      print('${entry.key}:');
      for (final report in entry.value) {
        print('  📄 ${report.reportPath}');
        print('     Module: ${report.moduleName} | Type: ${report.reportType}');
      }
      print('');
    }
  }

  /// Clear all registered reports
  void clear() {
    _reports.clear();
  }
}
