include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Disable for entire package
    public_member_api_docs: false
    lines_longer_than_80_chars: false

    # CLI tools need print statements
    avoid_print: false

    # Too strict for readability in some cases
    cascade_invocations: false

    # Not an issue for CLI tools
    avoid_slow_async_io: false

    # Allow single-line if statements for simple cases
    curly_braces_in_flow_control_structures: false

    # Allow parameter reassignment in some cases
    parameter_assignments: false

    # We're already using very_good_analysis
    sort_pub_dependencies: false

    # Allow local variable type annotations when helpful
    omit_local_variable_types: false
    prefer_final_locals: false

    # Style preferences
    prefer_int_literals: false
    use_raw_strings: false

    # Allow dangling library comments
    dangling_library_doc_comments: false
    comment_references: false

    # Allow require_trailing_commas to be flexible
    require_trailing_commas: false

    # Constructor ordering is fine as-is
    sort_constructors_first: false

    # Allow TODO comments in any style
    flutter_style_todos: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    # Treat these as warnings instead of info
    unused_import: warning
    unused_local_variable: warning
