# GitHub Actions workflow for Dart/Flutter projects using test_reporter
#
# This workflow provides:
# - Multi-version Dart testing (stable + latest)
# - Dependency caching for faster builds
# - Full test suite analysis with flaky detection
# - Coverage threshold enforcement
# - Report artifacts upload
# - PR comments with test summary (optional)
#
# Usage:
# 1. Copy this file to .github/workflows/test.yml
# 2. Customize environment variables below
# 3. Commit and push

name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  # Customize these values for your project
  MIN_COVERAGE: 80
  TEST_RUNS: 3
  DART_SDK: stable

jobs:
  analyze:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK }}

      - name: Install dependencies
        run: dart pub get

      - name: Analyze code
        run: dart analyze --fatal-infos

      - name: Check formatting
        run: dart format --set-exit-if-changed .

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: analyze

    strategy:
      matrix:
        sdk: [stable, beta]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: dart pub get

      - name: Run test suite analysis
        run: |
          dart run test_reporter:analyze_suite test/ \
            --runs=${{ env.TEST_RUNS }} \
            --verbose

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ matrix.sdk }}
          path: tests_reports/
          retention-days: 14

  coverage:
    name: Coverage Check
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK }}

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: dart pub get

      - name: Check coverage threshold
        run: |
          dart run test_reporter:analyze_coverage lib/src \
            --min-coverage=${{ env.MIN_COVERAGE }} \
            --verbose

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: tests_reports/quality/
          retention-days: 14

  # Optional: PR comment with test summary
  # Uncomment to enable
  #
  # pr-comment:
  #   name: PR Summary
  #   runs-on: ubuntu-latest
  #   needs: [test, coverage]
  #   if: github.event_name == 'pull_request'
  #
  #   steps:
  #     - name: Download test reports
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: test-reports-stable
  #         path: reports/
  #
  #     - name: Create PR comment
  #       uses: actions/github-script@v7
  #       with:
  #         script: |
  #           const fs = require('fs');
  #           const suiteReport = fs.readFileSync('reports/suite/latest_report.md', 'utf8');
  #
  #           github.rest.issues.createComment({
  #             issue_number: context.issue.number,
  #             owner: context.repo.owner,
  #             repo: context.repo.repo,
  #             body: `## Test Report\n\n${suiteReport.substring(0, 4000)}`
  #           });

# Workflow variants:
#
# For Flutter projects, replace dart-lang/setup-dart with:
#   - uses: subosito/flutter-action@v2
#     with:
#       flutter-version: stable
#
# For faster CI, use parallel testing:
#   - dart run test_reporter:analyze_tests test/ --parallel --runs=3
#
# For strict coverage enforcement:
#   - dart run test_reporter:analyze_coverage lib/src --min-coverage=90 --fail-on-decrease
#
# For baseline comparison (requires baseline.json in repo):
#   - dart run test_reporter:analyze_coverage lib/src --baseline=coverage-baseline.json --fail-on-decrease
